/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Deber_03_07.Vista;

import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.JInternalFrame;
import Deber_03_07.Modelo.Personaje;
import Deber_03_07.Modelo.Actor;
import Deber_03_07.Modelo.Pelicula;
import Deber_03_07.Servicio.PersonajeServiceImpl;
import Deber_03_07.Servicio.ActorServiceImpl;
import Deber_03_07.Servicio.PeliculaServiceImpl;

/**
 *
 * @author SrJuano
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private Ventana_Pelicula_Crear ventanaPeliculaCrear;
    private Ventana_Pelicula_Modificar ventanaPeliculaModificar;
    private Ventana_Pelicula_Eliminar ventanaPeliculaEliminar;
    private Ventana_Pelicula_Listar ventanaPeliculaListar;

    private Ventana_Actor_Crear ventanaActorCrear;
    private Ventana_Actor_Modificar ventanaActorModificar;
    private Ventana_Actor_Eliminar ventanaActorEliminar;
    private Ventana_Actor_Listar ventanaActorListar;

    private Ventana_Personaje_Crear ventanaPersonajeCrear;
    private Ventana_Personaje_Modificar ventanaPersonajeModificar;
    private Ventana_Personaje_Eliminar ventanaPersonajeEliminar;
    private Ventana_Personaje_Listar ventanaPersonajeListar;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1180, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 829, Short.MAX_VALUE)
        );

        jMenu2.setText("PELICULA");

        jMenuItem1.setText("Crear");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Modificar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem11.setText("Eliminar");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem11);

        jMenuItem3.setText("Listar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("ACTOR");

        jMenuItem5.setText("Crear");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem6.setText("Modificar");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem12.setText("Eliminar");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem12);

        jMenuItem7.setText("Listar");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("PERSONAJE");

        jMenuItem8.setText("Crear");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        jMenuItem9.setText("Modificar");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem9);

        jMenuItem13.setText("Eliminar");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem13);

        jMenuItem10.setText("Listar");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem10);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        this.ventanaPeliculaListar = new Ventana_Pelicula_Listar();
        ventanaPeliculaListar.setVisible(true);
        ventanaPeliculaListar.setResizable(true);
        ventanaPeliculaListar.setDefaultCloseOperation(JInternalFrame.DISPOSE_ON_CLOSE);
        ventanaPeliculaListar.setClosable(true);
        ventanaPeliculaListar.setIconifiable(true);
        this.jDesktopPane1.add(this.ventanaPeliculaListar);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        this.ventanaActorEliminar = new Ventana_Actor_Eliminar();
        ventanaActorEliminar.setVisible(true);
        ventanaActorEliminar.setResizable(true);
        ventanaActorEliminar.setDefaultCloseOperation(JInternalFrame.DISPOSE_ON_CLOSE);
        ventanaActorEliminar.setClosable(true);
        ventanaActorEliminar.setIconifiable(true);

        this.jDesktopPane1.add(this.ventanaActorEliminar);

// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        this.ventanaPeliculaCrear = new Ventana_Pelicula_Crear();
        ventanaPeliculaCrear.setVisible(true);
        ventanaPeliculaCrear.setResizable(true);
        ventanaPeliculaCrear.setDefaultCloseOperation(JInternalFrame.DISPOSE_ON_CLOSE);
        ventanaPeliculaCrear.setClosable(true);
        ventanaPeliculaCrear.setIconifiable(true);

        this.jDesktopPane1.add(this.ventanaPeliculaCrear);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
   this.ventanaPeliculaModificar = new Ventana_Pelicula_Modificar();
        ventanaPeliculaModificar.setVisible(true);
        ventanaPeliculaModificar.setResizable(true);
        ventanaPeliculaModificar.setDefaultCloseOperation(JInternalFrame.DISPOSE_ON_CLOSE);
        ventanaPeliculaModificar.setClosable(true);
        ventanaPeliculaModificar.setIconifiable(true);

        this.jDesktopPane1.add(this.ventanaPeliculaModificar);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
  this.ventanaPeliculaEliminar = new Ventana_Pelicula_Eliminar();
        ventanaPeliculaEliminar.setVisible(true);
        ventanaPeliculaEliminar.setResizable(true);
        ventanaPeliculaEliminar.setDefaultCloseOperation(JInternalFrame.DISPOSE_ON_CLOSE);
        ventanaPeliculaEliminar.setClosable(true);
        ventanaPeliculaEliminar.setIconifiable(true);
        this.jDesktopPane1.add(this.ventanaPeliculaEliminar);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        this.ventanaActorCrear = new Ventana_Actor_Crear();
        ventanaActorCrear.setVisible(true);
        ventanaActorCrear.setResizable(true);
        ventanaActorCrear.setDefaultCloseOperation(JInternalFrame.DISPOSE_ON_CLOSE);
        ventanaActorCrear.setClosable(true);
        ventanaActorCrear.setIconifiable(true);

        this.jDesktopPane1.add(this.ventanaActorCrear);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        this.ventanaActorModificar = new Ventana_Actor_Modificar();
        ventanaActorModificar.setVisible(true);
        ventanaActorModificar.setResizable(true);
        ventanaActorModificar.setDefaultCloseOperation(JInternalFrame.DISPOSE_ON_CLOSE);
        ventanaActorModificar.setClosable(true);
        ventanaActorModificar.setIconifiable(true);

        this.jDesktopPane1.add(this.ventanaActorModificar);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        this.ventanaActorListar = new Ventana_Actor_Listar();
        ventanaActorListar.setVisible(true);
        ventanaActorListar.setResizable(true);
        ventanaActorListar.setDefaultCloseOperation(JInternalFrame.DISPOSE_ON_CLOSE);
        ventanaActorListar.setClosable(true);
        ventanaActorListar.setIconifiable(true);

        this.jDesktopPane1.add(this.ventanaActorListar);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        this.ventanaPersonajeCrear = new Ventana_Personaje_Crear();
        ventanaPersonajeCrear.setVisible(true);
        ventanaPersonajeCrear.setResizable(true);
        ventanaPersonajeCrear.setDefaultCloseOperation(JInternalFrame.DISPOSE_ON_CLOSE);
        ventanaPersonajeCrear.setClosable(true);
        ventanaPersonajeCrear.setIconifiable(true);

        this.jDesktopPane1.add(this.ventanaPersonajeCrear);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
 this.ventanaPersonajeModificar = new Ventana_Personaje_Modificar();
        ventanaPersonajeModificar.setVisible(true);
        ventanaPersonajeModificar.setResizable(true);
        ventanaPersonajeModificar.setDefaultCloseOperation(JInternalFrame.DISPOSE_ON_CLOSE);
        ventanaPersonajeModificar.setClosable(true);
        ventanaPersonajeModificar.setIconifiable(true);

        this.jDesktopPane1.add(this.ventanaPersonajeModificar);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
 this.ventanaPersonajeEliminar = new Ventana_Personaje_Eliminar();
        ventanaPersonajeEliminar.setVisible(true);
        ventanaPersonajeEliminar.setResizable(true);
        ventanaPersonajeEliminar.setDefaultCloseOperation(JInternalFrame.DISPOSE_ON_CLOSE);
        ventanaPersonajeEliminar.setClosable(true);
        ventanaPersonajeEliminar.setIconifiable(true);

        this.jDesktopPane1.add(this.ventanaPersonajeEliminar);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        this.ventanaPersonajeListar = new Ventana_Personaje_Listar();
        ventanaPersonajeListar.setVisible(true);
        ventanaPersonajeListar.setResizable(true);
        ventanaPersonajeListar.setDefaultCloseOperation(JInternalFrame.DISPOSE_ON_CLOSE);
        ventanaPersonajeListar.setClosable(true);
        ventanaPersonajeListar.setIconifiable(true);

        this.jDesktopPane1.add(this.ventanaPersonajeListar);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new VentanaPrincipal().setVisible(true);
                var peliculaServiceImpl = new PeliculaServiceImpl();
                List<Pelicula> peliculaList = peliculaServiceImpl.recuperarArchivo("C:/Netbeans1/pelicula.dat");
                peliculaServiceImpl.setUniversidadList(peliculaList);

                var actorServiceImpl = new ActorServiceImpl();
                List<Actor> actorlist = actorServiceImpl.recuperarArchivo("C:/Netbeans1/actor.dat");
                actorServiceImpl.setActorList(actorlist);

                var personajeServiceImpl = new PersonajeServiceImpl();
                List<Personaje> personajelist = personajeServiceImpl.recuperarArchivo("C:/Netbeans1/personaje.dat");
                personajeServiceImpl.setPersonajeList(personajelist);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables
}
